import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import runtime.Trace;
import runtime.ReportGenerator;

/**
 * Generated by coverage calculator. Run this test suite in order to generate a coverage report
 * for all test classes.
 */
@RunWith(Suite.class)
public class TestCoverageRunner {

    @BeforeClass
    public static void coverageSetup() {
        System.out.println("Generating coverage report for module '" + sourceModuleName + "'.");
        System.out.println("  Preparing trace...");
        Trace.getInstance().reset();
        System.out.println("  Running tests...");
    }

    @AfterClass
    public static void coverageWrapup() {
        System.out.println("  Generating coverage report files...");
        new ReportGenerator().generate();
        System.out.println("Generating coverage report complete.");
    }
}

