package parser;

import com.github.javaparser.ast.Modifier;
import com.github.javaparser.ast.body.CallableDeclaration;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;

import java.util.*;

/**
 * Visits all methods and constructors and generates corresponding ProjectStructureNodes.
 */
class MethodNodeVisitor extends VoidVisitorAdapter<Void> {

    private final Collection<ProjectStructureNode> nodes;
    private final ProjectStructureNode parent;

    /**
     * @param parent The parent node (e.g. containing class)
     */
    MethodNodeVisitor(ProjectStructureNode parent) {
        this.nodes = new HashSet<>();
        this.parent = parent;
    }

    private void processCallable(CallableDeclaration callable, EnumSet<Modifier> modifiers,
                                 String type) {
        String name = callable.getSignature().asString();
        List<String> signatureTokens = new ArrayList<>();
        for (Modifier modifier : modifiers) {
            signatureTokens.add(modifier.asString());
        }
        if (type != null) {
            signatureTokens.add(type);
        }
        signatureTokens.add(name);
        String signature = String.join(" ", signatureTokens);
        String javaPath = parent.getJavaPath() + "." + name;
        nodes.add(new ProjectStructureNode(CODE_UNIT.METHOD, name, signature,
                parent.getFilePath(), javaPath));
    }

    /**
     * Generate a ProjectStructureNode corresponding to a method and add it to the visitors nodes
     * field.
     *
     * @param method The method to visit
     * @param v
     */
    public void visit(MethodDeclaration method, Void v) {
        processCallable(method, method.getModifiers(), method.getType().asString());
    }

    /**
     * Generate a ProjectStructureNode corresponding to a constructor and add it to the visitors
     * nodes field.
     *
     * @param constructor The constructor to visit
     * @param v
     */
    public void visit(ConstructorDeclaration constructor, Void v) {
        processCallable(constructor, constructor.getModifiers(), null);
    }

    /**
     * Retrieve the generated collection of nodes.
     *
     * @return All nodes generated by this visitor
     */
    Collection<ProjectStructureNode> getNodes() {
        return nodes;
    }
}
